### ISSUE TITLE
I'd like to translate the UI to Norwegian

### ISSUE THREAD

**Issue by haraldgroven** [hatnote/top#1]

**Comment by mahmoud** [comment]
Sounds great! Let's first start data collection for Norwegian and make sure everything is running smoothly and then we'll get you some strings worth translating :)

**Comment by haraldgroven** [comment]
Great, and thanks a lot!

**Comment by slaporte** [comment]
I'm still setting up the UI for translating, but the NO edition is available [here](http://top.hatnote.com/no/).

**Comment by haraldgroven** [comment]
Thank you! I have posted a link to top.hatnote.com/no/ on the Norwegian Bokmål "village pump" discussion forum.

**Comment by slaporte** [comment]
Excellent, thank you! If you can help translate, just make a copy of [this file](https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml) in Norwegian.
