### ISSUE TITLE
Local Number

### ISSUE THREAD

**Issue by reza1615** [hatnote/top#19]
Please set local number as article counter, date, page vesite number, statistic numbers. 
for example at
http://top.hatnote.com/fa/wikipedia/2016/5/10.html
10 مهٔ 2016 should be ۱۰ مهٔ ۲۰۱۶

**Comment by reza1615** [comment]
(123).toLocaleString('fa')

**Comment by slaporte** [comment]
We use abbreviated numbers (16,000 -> 16K) in a few places in the interface. How do I shorten numbers in Persian?

**Comment by reza1615** [comment]
after it converted to 16K put it inside the function.
(16K).toLocaleString('fa') = >  ۱۶K

**Comment by reza1615** [comment]
also converting numbers for the dates and article counters
16 مهٔ 2016 > 
۱۶ مهٔ ۲۰۱۶

**Comment by reza1615** [comment]
![01](https://cloud.githubusercontent.com/assets/2202483/15368913/77fd7f16-1d45-11e6-8ae1-2b5c93e4a38c.png)
Like this screenshot

**Comment by slaporte** [comment]
I've updated the numbers. Does everything look right? http://top.hatnote.com/fa/

**Comment by reza1615** [comment]
Thank you that is ok :)
