### ISSUE TITLE
Page titile for Latvian says "English Wikipedia"

### ISSUE THREAD

**Issue by papuass** [hatnote/top#22]
Page titile/heading and RSS feed for Latvian says "English Wikipedia"
http://top.hatnote.com/lv/

It has been that way for a few days.

**Comment by slaporte** [comment]
Ouch, sorry about that. It's all fixed going forward, although the archives will need to be updated at some point. If you have a moment to help translate the interface, you can send a pull request with this file for Latvian: https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml
