### ISSUE TITLE
Top 100 Article from Punjab Wikipedia

### ISSUE THREAD

**Issue by grubaz** [hatnote/top#23]
I'd like to volunteer to translate the templates required for displaying Top 100 articles from Punjab Wikipedia. pa.wikipedia.org

**Comment by slaporte** [comment]
Great, thank you! You can make a copy of [this file](https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml) to submit a translation into Punjab.

**Comment by grubaz** [comment]
Hello I have submitted the file in a Pull Request.

**Comment by slaporte** [comment]
Looks good. The Punjabi charts are now up here: http://top.hatnote.com/pa/
