### ISSUE TITLE
404.php popular in enwiki

### ISSUE THREAD

**Issue by papuass** [hatnote/top#25]
It has been a few weeks since https://en.wikipedia.org/wiki/404.php page has been on top for English Wikipedia, see: http://top.hatnote.com/en/wikipedia/2016/10/26.html
Not sure if it is that popular, but certainly is not very interesting.

**Comment by slaporte** [comment]
That looks very strange, especially considering the [traffic difference](https://tools.wmflabs.org/pageviews/?project=en.wikipedia.org&platform=all-access&agent=user&range=latest-20&pages=HTTP_404|404.php) between HTTP 404 and 404.php (which should be a redirect). I suspect this is either a bot or a fluke in the traffic stats. 

Starting today, we'll filter out 404.php from the results.
