### ISSUE TITLE
Top 100 from Odia Wikipedia

### ISSUE THREAD

**Issue by mkwiki** [hatnote/top#27]
Please add Odia Wikipedia (or.wikipedia.org) Top 100

**Comment by slaporte** [comment]
Sure thing! Could you create a copy of [this file](https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml), and translate the interface into Odia? Let me know if you have any questions.

**Comment by mkwiki** [comment]
Partial Odia translation is ready.

**Comment by psubhashish** [comment]
@slaporte Hi, I used the partial translation made by @mkwiki and finished the rest [here](https://github.com/OdiaWikimedia/top/blob/master/top/templates/strings/or_strings.yaml). I have also created a [pull request](https://github.com/hatnote/top/pull/30). Can you please add Odia (language code "or")?

**Comment by slaporte** [comment]
Odia is up here: http://top.hatnote.com/or/ Thank you, and enjoy!
