### ISSUE TITLE
Finnish

### ISSUE THREAD

**Issue by susannaanas** [hatnote/top#28]
I'm keen to translate to Finnish. Good work!

**Comment by mahmoud** [comment]
Thanks! All you need to do is make a Finnish version of this file: https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml

A bit of html knowledge might help, but basically if you just work around anything in angle brackets (`<>`) you should be fine. Thanks in advance!

**Comment by slaporte** [comment]
Finnish is up and running! http://top.hatnote.com/fi/

Thanks for sending translations so quickly.
