### ISSUE TITLE
image backlist

### ISSUE THREAD

**Issue by reza1615** [hatnote/top#41]
where can we define not to show an image?

**Comment by slaporte** [comment]
The image filter list is in [/top/word_filter.py](https://github.com/hatnote/top/blob/master/top/word_filter.py). If any words on that list match part of the filename, it will display the "W" instead. It also won't go back and remove images from the archive, so let me know if there are particular days you're worried about.

**Comment by reza1615** [comment]
@slaporte please remove [this image](https://commons.wikimedia.org/wiki/File:Ejaculation_educational_seq_4.png?uselang=fa) from [this article](http://top.hatnote.com/fa/wikipedia/2018/3/31.html#title-%D8%A7%D9%86%D8%B2%D8%A7%D9%84) image

**Comment by reza1615** [comment]
also, there is [a list](https://en.wikipedia.org/wiki/MediaWiki:Bad_image_list) on Wikipedia which can help

**Comment by slaporte** [comment]
Thanks @reza1615! I've added a filter for those files.
