### ISSUE TITLE
http://top.hatnote.com is stopped

### ISSUE THREAD

**Issue by reza1615** [hatnote/top#43]
Since 23rd March http://top.hatnote.com/fa/ is stoped and not updated.

**Comment by mahmoud** [comment]
Thanks for the report @reza1615! Yes, unfortunately some backend APIs seem to have changed, and all languages have been affected. We are tracking this issue here as well: https://phabricator.wikimedia.org/T219718

We'll be back up ASAP!

**Comment by mahmoud** [comment]
@reza1615 all fixed, baz tashakor mikonim! :)
