### ISSUE TITLE
List of the most visited articles in Galician

### ISSUE THREAD

**Issue by Elisardojm** [hatnote/top#49]
Hi, I wanted this tool to publish the list of the most viewed articles in Galician. What templates need to be translated? Thank you very much.

**Comment by slaporte** [comment]
Thanks for your help translating! If you can make a copy of [this file](https://github.com/hatnote/top/blob/master/top/templates/strings/en_strings.yaml), translate into Galician, and either post here or open a pull request. I'll take care of the rest!

If you're interested in a weekly email newsletter with the most-edited articles, there's a similar process for translating that [here](https://github.com/hatnote/weeklypedia/blob/master/README.md#localization).

**Comment by Elisardojm** [comment]
#------------------
# Wikipedia Top 100
#    If you want to translate the charts on top.hatnote.com, start with a copy
#    of this file and leave us a note at:
#    https://github.com/hatnote/top/issues
#------------------------------------------------------------------------------

#-----------
# Page title
#------------------------------------------------------------------------------

title: Top 100
full_title: >-
  Top 100 da Wikipedia en galego o {formatted_date}
index_title: >-
  Top 100 Wikipedia en galego
rss_title: >-
  Os 100 artigos máis visitados da Wikipedia en galego
wikipedia: Wikipedia
language_project: Wikipedia en galego
tagline: >-
    Os artigos máis visitados da Wikipedia en galego, actualizados diariamente. <a
    href="#about" class="learn">Saber máis</a>...
alt_tagline: >-
    Os artigos máis visitados da Wikipedia en galego, actualizados diariamente.
#------
# Links
#------------------------------------------------------------------------------

about_link: Acerca de
more_langs_link: Máis linguas
feed_link: Feed
blog_link: Blog
top: Volver arriba

#---------
# Articles
#
#   Each article has statistics at the bottom like this:
#   934.8K views (↑300.5K from yesterday)
#------------------------------------------------------------------------------

views: visitas
from_yesterday: de onte
streak: días na lista

#------------
# About section
#------------------------------------------------------------------------------

about_header: Acerca de
about_section: >-
     <p>Consulta o <a href="http://top.hatnote.com/gl/wikipedia">arquivo</a>.</p>
     <p>Unha lista diaria dos artigos de Wikipedia máis visitados, xerada por <a href="https://twitter.com/sklaporte">Stephen LaPorte</a>
     e <a href="https://twitter.com/mhashemi">Mahmoud
     Hashemi</a>. Tamén está dispoñible en <a
     href="http://top.hatnote.com/about.html">máis linguas</a>. Se esta lista che parece interesante, disfrutarás de <a
     href="http://weekly.hatnote.com">The Weeklypedia</a>, un resumo semanal dos artigos de Wikipedia máis editados. Máis información no <a
     href="#">Blog de Hatnote</a>.</p>
     <p>Esta páxina foi posible grazas á <a
     href="https://wikimedia.org/api/rest_v1/?doc#!/Pageviews_data/get_metrics_\
     pageviews_top_project_access_year_month_day">nova API de visitas de artigos da Wikipedia</a>, con algunhas bonitas imaxes e resumos de <a
     href="https://www.mediawiki.org/wiki/API:Query">MediaWiki
     API</a>. Podes atopar máis código e documentación en <a
     href="https://github.com/hatnote/top">github</a>.</p>
     <p>Queres ver unha lista dos artigos máis visitados noutra 
     lingua de Wikipedia? Nós tamén! Por favor <a
     href="https://github.com/hatnote/top/issues">envía unha petición</a>
     e fainos saber se podes axudar a traducir os modelos.</p>
     <p><a href="https://twitter.com/hatnotable">@hatnotable</a></p>
#------- 
# Tweets 
#
#   We can provide three possible tweets. They shouldn't be longer than 117 
#   characters (including the article title, so there is enough space to 
#   include a link.
#------------------------------------------------------------------------------

long_tweet: >- 
    Nunha xeira de {streak} días, {title} foi o #{rank} artigo máis
    lido en #{project} c/ {views} visitas
medium_tweet: "{title} foi visto {views} veces en #{project}"
short_tweet: "{title} foi o #{rank} en #{project}"

#-------------
# Archive page
#------------------------------------------------------------------------------

all_traffic_data: Todos os datos de tráfico

#----
# RSS
#------------------------------------------------------------------------------

rss_intro: Xa están as novas estatísticas de Wikipedia en galego!
rss_description: >-
    <a href="{permalink|s}">{title}</a> pasou á posición #{rank}, con {views_short} 
    visitas{?streak_min}, continuando a súa xeira de {streak_len} días na gráfica
    ({view_trend|s}{view_delta} visitas dende onte){/streak_min}.
rss_read_more: Ler mais...

**Comment by Elisardojm** [comment]
Hi, @slaporte, how is this issue?

**Comment by slaporte** [comment]
Thanks for the translation! It's set up here: https://top.hatnote.com/gl/

Let me know if you see any translation bugs.
