### ISSUE TITLE
Top pages for Persian (fa) Wikipedia

### ISSUE THREAD

**Issue by Ladsgroup** [hatnote/top#9]
Hey, That would be great. I can help with translation but I couldn't find the files to make a PR. Thanks

**Comment by mrphs** [comment]
Yeah I was also wondering what does it take to add Fa. I just quickly ran `python get_data.py --date 20160311 --lang fa --update` and it seemed to work perfectly fine. I suppose it's just a matter of making an RTL template.

**Comment by ArianAr** [comment]
@mahmoud any update on this issue? A lot of our users are eager to use this tool!

**Comment by Ladsgroup** [comment]
OK. I tried something but it seems we need to flip rank column too:
![image](https://cloud.githubusercontent.com/assets/5351225/15097040/ce7b5c6a-1524-11e6-8aba-ce34d31492e0.png)

Is that enough for now?

**Comment by mahmoud** [comment]
Hey all, the deed is now done: http://top.hatnote.com/fa/  Subscribe to the RSS: http://top.hatnote.com/feeds/fawikipedia.rss

I'll take a PR for a better layout, though it will have to include some switching for including an alternate template. As for what the layout should look like, I read it better like it is currently, but that may be due to my LTR habits. Just open a PR for that when it's ready. Thanks!

**Comment by mahmoud** [comment]
Also, and if this sparks any discussion on fa.wikipedia.org, someone link us to the talk page!

**Comment by reza1615** [comment]
I wrote a python code which translate and localize the page. it replace texts on index.html
If you want I can send it to check which parts should be localize for persian
https://tools.wmflabs.org/rezabot/top/static/fa/index.html

**Comment by reza1615** [comment]
[https://fa.wikipedia.org/wiki/%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D9%82%D9%87%D9%88%D9%87%E2%80%8C%D8%AE%D8%A7%D9%86%D9%87/%DA%AF%D9%88%D9%86%D8%A7%DA%AF%D9%88%D9%86#.D9.81.D9.87.D8.B1.D8.B3.D8.AA_.D9.BE.D8.B1_.D8.A8.DB.8C.D9.86.D9.86.D8.AF.D9.87.E2.80.8C.D8.AA.D8.B1.DB.8C.D9.86.E2.80.8C.D9.87.D8.A7](here) is discussion

**Comment by reza1615** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2202483/15099697/ce63c35a-1571-11e6-800c-93bfd1e84d6c.png)
